<?php
require '../../dataQuality/Helper.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-05 at 20:01:36.
 */
class HelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Helper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Helper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Helper::testUniqueness
     * @todo   Implement testTestUniqueness().
     */
    public function testTestUniqueness() {
        // Remove the following lines when you implement this test.
        echo "MATCH ".$this->object->testUniqueness("Fred Smith", "Fredy smith");
        
    }
    
    

}
