<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-07 at 03:58:24.
 */
require '../../dataQuality/importData/csvImport.php';
require '../../dataQuality/Sensor/Accelerometer.php';
class AccerlerometerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Accerlerometer
     */
    protected $object;
    protected $csvObject;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->csvObject = new csvImport(__DIR__."/file.csv");
        $this->object = new Accerlerometer($this->csvObject->getCSVData());
        
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Accerlerometer::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accerlerometer::getAccuracy
     * @todo   Implement testGetAccuracy().
     */
    public function testGetAccuracy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
         * @covers Accerlerometer::getUniqueness
     * @todo   Implement testGetUniqueness().
     */
    public function testGetUniqueness() {
        // Remove the following lines when you implement this test.
        echo "Uniqueness ".$this->object->getUniqueness();
    }

    /**
     * @covers Accerlerometer::getMissingValues
     * @todo   Implement testGetMissingValues().
     */
    public function testGetMissingValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
