<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-05 at 21:32:31.
 */
require '../../dataQuality/importData/csvImport.php';
require '../../dataQuality/Sensor/Data.php';
class DataTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Data
     */
    protected $object;
    protected $csvObject;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->csvObject = new csvImport(__DIR__ . "/file.csv");

        $this->object = new Data($this->csvObject->getCSVData());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Data::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Data::calculateUniqueness
     * @todo   Implement testCalculateUniqueness().
     */
    public function testCalculateUniqueness() {
        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
        echo "Executing...";
        
        $dataArray = $this->object->getData();
        
        print_r($dataArray);
        echo "Length ".count($dataArray);
    }

    /**
     * @covers Data::calculateCompleteness
     * @todo   Implement testCalculateCompleteness().
     */
    public function testCalculateCompleteness() {
        // Remove the following lines when you implement this test.

        /*
         * Missing value test
         */
    }

    /**
     * @covers Data::calculateTimeliness
     * @todo   Implement testCalculateTimeliness().
     */
    public function testCalculateTimeliness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Data::calculateValidity
     * @todo   Implement testCalculateValidity().
     */
    public function testCalculateValidity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Data::calculateAccuracy
     * @todo   Implement testCalculateAccuracy().
     */
    public function testCalculateAccuracy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Data::calculateConsistency
     * @todo   Implement testCalculateConsistency().
     */
    public function testCalculateConsistency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
