<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-05 at 21:05:53.
 */
class SensorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Sensor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Sensor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Sensor::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sensor::getAccuracy
     * @todo   Implement testGetAccuracy().
     */
    public function testGetAccuracy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sensor::getMissingValues
     * @todo   Implement testGetMissingValues().
     */
    public function testGetMissingValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
