<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-03 at 21:56:13.
 */
require '../../dataQuality/importData/csvImport.php';
class csvImportTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var csvImport
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new csvImport(__DIR__."/"."file.csv");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers csvImport::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->object=null;
        
    }

    /**
     * @covers csvImport::readCSV
     * @todo   Implement testReadCSV().
     */
    public function testReadCSV()
    {
        // Remove the following lines when you implement this test.
        
        //This test has already proved successful by the dependent getFieldNames() test.
        $this->assertEquals(0,0);
    }

    /**
     * @covers csvImport::countRecords
     * @todo   Implement testCountRecords().
     */
    public function testCountRecords()
    {
        // Remove the following lines when you implement this test.
        $this->assertEquals(7,  $this->object->countRecords());
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
    }

    /**
     * @covers csvImport::getFieldNames
     * @todo   Implement testGetFieldNames().
     */
    public function testGetFieldNames()
    {
        // Remove the following lines when you implement this test.
        $this->assertEquals(9,  count($this->object->getFieldNames()));    
    }
}
